import { AsientoEstado } from "../types/AsientoEstado";

export const plantillaPremium = [
  {
    id: "seat-001",
    x: 70,
    y: 10,
    label: "A1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-002",
    x: 110,
    y: 10,
    label: "A2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-003",
    x: 150,
    y: 10,
    label: "A3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-004",
    x: 190,
    y: 10,
    label: "A4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-005",
    x: 230,
    y: 10,
    label: "A5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-006",
    x: 270,
    y: 10,
    label: "A6",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-007",
    x: 310,
    y: 10,
    label: "A7",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-008",
    x: 350,
    y: 10,
    label: "A8",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-009",
    x: 390,
    y: 10,
    label: "A9",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-010",
    x: 70,
    y: 50,
    label: "B1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-011",
    x: 110,
    y: 50,
    label: "B2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-012",
    x: 150,
    y: 50,
    label: "B3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-013",
    x: 190,
    y: 50,
    label: "B4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-014",
    x: 230,
    y: 50,
    label: "B5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-015",
    x: 270,
    y: 50,
    label: "B6",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-016",
    x: 310,
    y: 50,
    label: "B7",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-017",
    x: 350,
    y: 50,
    label: "B8",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-018",
    x: 390,
    y: 50,
    label: "B9",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-019",
    x: 70,
    y: 165,
    label: "C1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-020",
    x: 110,
    y: 165,
    label: "C2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-021",
    x: 150,
    y: 165,
    label: "C3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-022",
    x: 190,
    y: 165,
    label: "C4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-023",
    x: 230,
    y: 165,
    label: "C5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-024",
    x: 270,
    y: 165,
    label: "C6",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-025",
    x: 310,
    y: 165,
    label: "C7",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-026",
    x: 350,
    y: 165,
    label: "C8",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-027",
    x: 390,
    y: 165,
    label: "C9",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-028",
    x: 70,
    y: 205,
    label: "D1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-029",
    x: 110,
    y: 205,
    label: "D2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-030",
    x: 150,
    y: 205,
    label: "D3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-031",
    x: 190,
    y: 205,
    label: "D4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-032",
    x: 230,
    y: 205,
    label: "D5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-033",
    x: 270,
    y: 205,
    label: "D6",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-034",
    x: 310,
    y: 205,
    label: "D7",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-035",
    x: 350,
    y: 205,
    label: "D8",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-036",
    x: 390,
    y: 205,
    label: "D9",
    estado: AsientoEstado.AVAILABLE,
  },
];

export const plantillaEstandar = [
  {
    id: "seat-001",
    x: 70,
    y: 10,
    label: "A1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-002",
    x: 110,
    y: 10,
    label: "A2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-003",
    x: 150,
    y: 10,
    label: "A3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-004",
    x: 190,
    y: 10,
    label: "A4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-005",
    x: 230,
    y: 10,
    label: "A5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-006",
    x: 270,
    y: 10,
    label: "A6",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-007",
    x: 310,
    y: 10,
    label: "A7",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-008",
    x: 350,
    y: 10,
    label: "A8",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-009",
    x: 390,
    y: 10,
    label: "A9",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0010",
    x: 430,
    y: 10,
    label: "A10",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0011",
    x: 470,
    y: 10,
    label: "A11",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-0012",
    x: 70,
    y: 50,
    label: "B1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0013",
    x: 110,
    y: 50,
    label: "B2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0014",
    x: 150,
    y: 50,
    label: "B3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0015",
    x: 190,
    y: 50,
    label: "B4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0016",
    x: 230,
    y: 50,
    label: "B5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0017",
    x: 270,
    y: 50,
    label: "B6",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0018",
    x: 310,
    y: 50,
    label: "B7",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0019",
    x: 350,
    y: 50,
    label: "B8",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0020",
    x: 390,
    y: 50,
    label: "B9",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0021",
    x: 430,
    y: 50,
    label: "B10",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0022",
    x: 470,
    y: 50,
    label: "B11",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-0023",
    x: 70,
    y: 165,
    label: "C1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0024",
    x: 110,
    y: 165,
    label: "C2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0025  ",
    x: 150,
    y: 165,
    label: "C3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0022",
    x: 190,
    y: 165,
    label: "C4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0023",
    x: 230,
    y: 165,
    label: "C5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0024",
    x: 270,
    y: 165,
    label: "C6",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0025",
    x: 310,
    y: 165,
    label: "C7",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0026",
    x: 350,
    y: 165,
    label: "C8",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0027",
    x: 390,
    y: 165,
    label: "C9",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0028",
    x: 430,
    y: 165,
    label: "C10",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0029",
    x: 470,
    y: 165,
    label: "C11",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-0030",
    x: 70,
    y: 205,
    label: "D1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0031",
    x: 110,
    y: 205,
    label: "D2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0032",
    x: 150,
    y: 205,
    label: "D3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0033",
    x: 190,
    y: 205,
    label: "D4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0034",
    x: 230,
    y: 205,
    label: "D5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0035",
    x: 270,
    y: 205,
    label: "D6",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0036",
    x: 310,
    y: 205,
    label: "D7",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0037",
    x: 350,
    y: 205,
    label: "D8",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0038",
    x: 390,
    y: 205,
    label: "D9",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0039",
    x: 430,
    y: 205,
    label: "D10",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-0040",
    x: 470,
    y: 205,
    label: "D11",
    estado: AsientoEstado.AVAILABLE,
  },
];

export const plantillaShuttle = [
  {
    id: "seat-001",
    x: 70,
    y: 10,
    label: "A1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-002",
    x: 110,
    y: 10,
    label: "A2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-003",
    x: 150,
    y: 10,
    label: "A3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-004",
    x: 190,
    y: 10,
    label: "A4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-005",
    x: 230,
    y: 10,
    label: "A5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-006",
    x: 270,
    y: 10,
    label: "A6",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-010",
    x: 70,
    y: 50,
    label: "B1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-011",
    x: 110,
    y: 50,
    label: "B2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-012",
    x: 150,
    y: 50,
    label: "B3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-013",
    x: 190,
    y: 50,
    label: "B4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-014",
    x: 230,
    y: 50,
    label: "B5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-015",
    x: 270,
    y: 50,
    label: "B6",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-019",
    x: 70,
    y: 165,
    label: "C1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-020",
    x: 110,
    y: 165,
    label: "C2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-021",
    x: 150,
    y: 165,
    label: "C3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-022",
    x: 190,
    y: 165,
    label: "C4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-023",
    x: 230,
    y: 165,
    label: "C5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-024",
    x: 270,
    y: 165,
    label: "C6",
    estado: AsientoEstado.AVAILABLE,
  },

  {
    id: "seat-028",
    x: 70,
    y: 205,
    label: "D1",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-029",
    x: 110,
    y: 205,
    label: "D2",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-030",
    x: 150,
    y: 205,
    label: "D3",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-031",
    x: 190,
    y: 205,
    label: "D4",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-032",
    x: 230,
    y: 205,
    label: "D5",
    estado: AsientoEstado.AVAILABLE,
  },
  {
    id: "seat-033",
    x: 270,
    y: 205,
    label: "D6",
    estado: AsientoEstado.AVAILABLE,
  },
];
