export const privilegiosSeeds = [
  { nombre: 'usuarios:crear', descripcion: 'Crear cuentas y asignar roles.' },
  { nombre: 'usuarios:consultar', descripcion: 'Consultar cuentas de usuario.' },
  { nombre: 'usuarios:editar', descripcion: 'Editar datos de usuario.' },
  { nombre: 'usuarios:estado', descripcion: 'Activar o desactivar usuarios.' },
  { nombre: 'usuarios:eliminar', descripcion: 'Eliminar cuentas de usuario.' },
  { nombre: 'roles:consultar', descripcion: 'Consultar roles y sus privilegios.' },
  { nombre: 'privilegios:consultar', descripcion: 'Consultar el catalogo de privilegios.' },
  { nombre: 'salida:consultar', descripcion: 'Consultar salidas programadas.' },
  { nombre: 'autobus:consultar', descripcion: 'Consultar autobuses.' },
  {
    nombre: 'ruta:crear',
    descripcion: 'Definir origen, destino y paradas..',
  },
  {
    nombre: 'viaje:editar',
    descripcion: 'Modificar rutas o servicios asociados.',
  },
  {
    nombre: 'viaje:abrir',
    descripcion: 'Generar salidas en calendario.',
  },
  {
    nombre: 'salida:cancelar',
    descripcion: 'Cancelar una instancia específica.',
  },
  {
    nombre: 'salida:reasignar',
    descripcion: 'Cambiar unidad o conductor en una salida.',
  },
  {
    nombre: 'calendario:consultar',
    descripcion: 'Consultar todos los viajes.',
  },
  {
    nombre: 'conductores:consultar',
    descripcion: 'Conductor solo ve lo suyo.',
  },
  { nombre: 'autobus:crear', descripcion: 'Registrar una unidad de transporte.' },
  { nombre: 'autobus:editar', descripcion: 'Modificar una unidad de transporte.' },
  { nombre: 'autobus:eliminar', descripcion: 'Dar de baja una unidad.' },
  { nombre: 'conductores:crear', descripcion: 'Registrar un conductor.' },
  { nombre: 'conductores:editar', descripcion: 'Actualizar un conductor.' },
  { nombre: 'conductores:eliminar', descripcion: 'Dar de baja un conductor.' },
  { nombre: 'servicio:crear', descripcion: 'Definir un servicio adicional.' },
  { nombre: 'servicio:editar', descripcion: 'Modificar un servicio adicional.' },
  { nombre: 'servicio:eliminar', descripcion: 'Retirar un servicio del catalogo.' },
  { nombre: 'viaje-base:crear', descripcion: 'Crear una plantilla de viaje base.' },
  { nombre: 'viaje-base:editar', descripcion: 'Modificar una plantilla de viaje base.' },
  { nombre: 'viaje-base:eliminar', descripcion: 'Eliminar una plantilla de viaje base.' },
  { nombre: 'viaje-base:consultar', descripcion: 'Consultar viajes base disponibles.' },
  { nombre: 'ruta:consultar', descripcion: 'Visualizar rutas y trayectos.' },
  { nombre: 'ruta:editar', descripcion: 'Modificar una ruta o sus paradas.' },
  { nombre: 'ruta:eliminar', descripcion: 'Dar de baja una ruta.' },
  { nombre: 'parada:crear', descripcion: 'Registrar una parada.' },
  { nombre: 'parada:editar', descripcion: 'Modificar una parada.' },
  { nombre: 'parada:eliminar', descripcion: 'Retirar una parada.' },
  { nombre: 'reportes:consultar', descripcion: 'Consultar reportes operativos.' },
];
